sudo: false
language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"

env:
  - DJANGO=1.9
  - DJANGO=1.10

matrix:
  fast_finish: true
  allow_failures:
  - env: DJANGO=1.10

before_install: pip install codecov
install: pip install tox-travis
script: tox
after_success: codecov
